"""firstMigration

Revision ID: 1ded0770fb2e
Revises: 
Create Date: 2023-10-26 16:21:14.732074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ded0770fb2e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('count',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('accessCount', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cpf', sa.String(length=16), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('carPlate', sa.String(length=16), nullable=True),
    sa.Column('phoneNumber', sa.String(length=16), nullable=True),
    sa.Column('CEP', sa.String(length=32), nullable=True),
    sa.Column('birthDate', sa.DateTime(), nullable=True),
    sa.Column('paymentMethod', sa.String(), nullable=True),
    sa.Column('soleOccupation', sa.Boolean(), nullable=True),
    sa.Column('appDriverMonths', sa.Integer(), nullable=True),
    sa.Column('uberCategory', sa.String(), nullable=True),
    sa.Column('rentalCar', sa.Boolean(), nullable=True),
    sa.Column('dailyWorkTime', sa.Integer(), nullable=True),
    sa.Column('uberRating', sa.Float(), nullable=True),
    sa.Column('totalTrips', sa.Integer(), nullable=True),
    sa.Column('carModel', sa.String(length=64), nullable=True),
    sa.Column('workArea', sa.String(length=100), nullable=True),
    sa.Column('workInterest', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phoneNumber')
    )
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drivers_carPlate'), ['carPlate'], unique=True)
        batch_op.create_index(batch_op.f('ix_drivers_cpf'), ['cpf'], unique=True)
        batch_op.create_index(batch_op.f('ix_drivers_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_drivers_name'), ['name'], unique=False)

    op.create_table('anuncios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('createDate', sa.DateTime(), nullable=False),
    sa.Column('updateDate', sa.DateTime(), nullable=False),
    sa.Column('driverId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['driverId'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('anuncios')
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drivers_name'))
        batch_op.drop_index(batch_op.f('ix_drivers_email'))
        batch_op.drop_index(batch_op.f('ix_drivers_cpf'))
        batch_op.drop_index(batch_op.f('ix_drivers_carPlate'))

    op.drop_table('drivers')
    op.drop_table('count')
    # ### end Alembic commands ###
